name: "Build Dark Ages kernel on darky."              # Description of the workflow.
on:
  push:
    branches:
      - darky                                         # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build Dark Ages kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3             # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
        defconfig: vince_defconfig                    # Specify defconfig to use
        image: Image.gz-dtb
    - name: Upload Release
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{steps.sign.outputs.signedReleaseFile}}
        asset_name: kernel.zip
        asset_content_type: zip
 
